### ISSUE TITLE
Error in ckad/2/2/Task 2/Step 1

### ISSUE THREAD

**Issue by ash3rr** [nigelpoulton/ckad#22]
blue.deploy.yml
green.deploy.yml

both refer to image ckad:green / ckad:blue results in ImagePullBackOff

Error:
Failed to pull image "ckad:blue": rpc error: code = Unknown desc = Error response from daemon: failed to resolve reference "docker.io/library/ckad:blue": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     81s (x4 over 3m1s)  kubelet            Error: ErrImagePul

**Comment by nigelpoulton** [comment]
@DanWahlin Hi Dan. Is there anything needed on this?

**Comment by NeonDemon-88** [comment]
Hi,

The same problem still persists, even though the `docker-compose build`- command is ran to get the images. The images are there when I check them with `docker images`-command, but when trying to do the Blue/Green and Canary/Stable deployments the pods suddenly aren't able to pull the images, and are failing with errors such as  _ImagePullBackOff_ and _ErrImagePull_. I'm not sure if this is due to me using minikube, but currently I'm not able to finish these tasks due to this error.

**Comment by DanWahlin** [comment]
Hi @NeonDemon-88. Sorry you're hitting an issue. The initial issue reported here was a different scenario since they didn't have the images on their machine. 

I wanted to double-check things, so I just cloned the repo from scratch and tried the steps and everything seems to be working correctly on my Mac and Windows machines (I'm using Docker Desktop there) as well as on my full k8s cluster on Linux. So, I suspect there's something going on with your setup and it being able to pull the local images.

There's an `imagePullPolicy: IfNotPresent` set in the deployment files to ensure it looks locally for the images first so that shouldn't be the issue. However, you might try `imagePullPolicy: Never` in the deployment files to see if that affects your setup at all. I'm not sure if Minikube does anything different when it comes to pulling local images - haven't used it in a long time. I seem to remember having to do something like `eval $(minikube docker-env)` to set the Docker environment with Minikube but I don't know if that's still a thing now days (and you may be using a different container runtime). If there's still a problem with `imagePullPolicy: Never` - and the images match with the image names in the deployment files....which they should by default - then there's definitely something else going on.

You might try to run a `kubectl describe pod [pod-name]` to see if there are any additional details shown such as permissions errors. Normally `ErrImagePull` is pretty clear, but if you have images like "ckad:stable", etc. on your machine there must be something else going on there. I hope that points you in the right direction.

**Comment by NeonDemon-88** [comment]
Hi @DanWahlin, the `eval $(minikube docker-env)` seemed to do the trick! Thanks! :)

**Comment by DanWahlin** [comment]
Excellent!

**Comment by DanWahlin** [comment]
@nigelpoulton: Another issue to close out when you can.

**Comment by nigelpoulton** [comment]
Cheers @DanWahlin and @NeonDemon-88
